<?php

namespace App\Tests\Controller;

use App\Entity\Point;
use App\Entity\Set;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class RouteControllerTest extends WebTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->entityManager = self::getContainer()->get('doctrine')->getManager();

    }

    public function testCreateRoute(): void
    {
        $client = static::createClient();
        $set = new Set();
        $set->setName('testowy zbiór');

        $this->entityManager->persist($set);

        foreach(range(0, 5) as $range) {
            $point = new Point();
            $point->setX(19.145136);
            $point->setY(51.919438);
            $point->setSet($set);
            $point->setWeight(300);

            $this->entityManager->persist($set);
        }

        $this->entityManager->flush();


        $crawler = $client->request('POST', '/route/generate/' . $set->getId(), [
            'maximum_duration' => 100,
            'maximum_distance' => 100,
            'radius' => 100,
        ]);

        self::assertResponseIsSuccessful();
        self::assertEquals();
    }
}
